[package]
name = "grmtools-app"
edition.workspace = true

[[bin]]
name = "grmtools-app"
path = "app.rs"

[build-dependencies]
cfgrammar = "0.13"
lrlex = "0.13"
lrpar = "0.13"

[dependencies]
cfgrammar = "0.13"
lrlex = "0.13"
lrpar = "0.13"
